version: "3.7"
services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
        ports:
            - 9090:9090
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        ports:
            - 3000:3000
    boot_node:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        command: sh run_beacon_node.sh
    beacon_node_1:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        depends_on:
            - boot_node
        command: sh run_beacon_node.sh
        environment:
            BOOT_NODES: "/dns4/boot_node/tcp/9000"
        command: sh run_beacon_node.sh
    beacon_node_2:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        depends_on:
            - boot_node
        command: sh run_beacon_node.sh
        environment:
            BOOT_NODES: "/dns4/boot_node/tcp/9000"
        command: sh run_beacon_node.sh
    beacon_node_3:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        depends_on:
            - boot_node
        command: sh run_beacon_node.sh
        environment:
            BOOT_NODES: "/dns4/boot_node/tcp/9000"
        command: sh run_beacon_node.sh
    beacon_node_4:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        depends_on:
            - boot_node
        command: sh run_beacon_node.sh
        environment:
            BOOT_NODES: "/dns4/boot_node/tcp/9000"
        command: sh run_beacon_node.sh
    validator_client_1:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        environment:
            BEACON_NODE: "beacon_node_1"
            FIRST_VALIDATOR: 0
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh
    validator_client_2:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        environment:
            BEACON_NODE: "beacon_node_2"
            FIRST_VALIDATOR: 4
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh
    validator_client_3:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        environment:
            BEACON_NODE: "beacon_node_3"
            FIRST_VALIDATOR: 8
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh
    validator_client_4:
        image: lighthouse:prebuilt
        build:
            context: lighthouse
        environment:
            BEACON_NODE: "beacon_node_4"
            FIRST_VALIDATOR: 12
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh

volumes:
    grafana-data:
    prometheus-data:
