version: "3.7"
services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
        ports:
            - 9090:9090
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        ports:
            - 3000:3000
    beacon_node:
        build:
            context: lighthouse
        command: sh run_beacon_node.sh
    validator_client:
        build:
            context: lighthouse
        environment:
            BEACON_NODE: "beacon_node"
            FIRST_VALIDATOR: 0
            LAST_VALIDATOR: 16
        command: sh run_validator_client.sh

volumes:
    grafana-data:
    prometheus-data:
