version: "3.7"
services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
        ports:
            - 9090:9090
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        ports:
            - 3000:3000
    boot_node:
        build:
            context: lighthouse
        command: sh run_beacon_node.sh
    beacon_node:
        build:
            context: lighthouse
        depends_on:
            - boot_node
        command: sh run_beacon_node.sh
        environment:
            BOOT_NODES: "/dns4/boot_node/tcp/9000"
        command: sh run_beacon_node.sh
    validator_client:
        build:
            context: lighthouse
        environment:
            BEACON_NODE: "beacon_node"
            FIRST_VALIDATOR: 0
            NUM_VALIDATORS: 16
        depends_on:
            - beacon_node
        command: sh run_validator_client.sh

volumes:
    grafana-data:
    prometheus-data:
