version: "3.0"

services:
    beacon_node:
        image: sigp/lighthouse:dev
        volumes:
            - ./.lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts
        ports:
            - 5052:5052
            - 5053:5053
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
    validator_client:
        image: sigp/lighthouse:dev
        volumes:
            - ./.lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts
        depends_on:
            - account_manager
            - beacon_node
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
    account_manager:
        image: sigp/lighthouse:dev
        volumes:
            - ./.lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts
            - ./secrets:/root/secrets
            - ./network:/root/network
        env_file: .env
        command: sh /root/scripts/create-validators.sh
