version: "3.7"
services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
        ports:
            - 9090:9090
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        ports:
            - 3000:3000
    boot_node:
        image: lighthouse:feature
        command: sh run_beacon_node.sh
        volumes:
            - boot-node:/root/.lighthouse/network
        ports:
            - 9000:9000
            - 5051:5051
            - 5052:5052
        environment:
            DISCOVERY_ADDR: "172.20.0.250"
        networks:
            default:
                ipv4_address: 172.20.0.250
    beacon_node_1:
        image: lighthouse:feature
        depends_on:
            - boot_node
        volumes:
            - boot-node:/bootnode
        command: sh run_beacon_node.sh
    beacon_node_2:
        image: lighthouse:feature
        depends_on:
            - boot_node
        volumes:
            - boot-node:/bootnode
        command: sh run_beacon_node.sh
    beacon_node_3:
        image: lighthouse:feature
        depends_on:
            - boot_node
        volumes:
            - boot-node:/bootnode
        command: sh run_beacon_node.sh
    beacon_node_4:
        image: lighthouse:feature
        depends_on:
            - boot_node
        volumes:
            - boot-node:/bootnode
        command: sh run_beacon_node.sh
    validator_client_1:
        image: lighthouse:feature
        environment:
            BEACON_NODE: "beacon_node_1"
            FIRST_VALIDATOR: 0
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh
    validator_client_2:
        image: lighthouse:feature
        environment:
            BEACON_NODE: "beacon_node_2"
            FIRST_VALIDATOR: 4
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh
    validator_client_3:
        image: lighthouse:feature
        environment:
            BEACON_NODE: "beacon_node_3"
            FIRST_VALIDATOR: 8
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh
    validator_client_4:
        image: lighthouse:feature
        environment:
            BEACON_NODE: "beacon_node_4"
            FIRST_VALIDATOR: 12
            NUM_VALIDATORS: 4
        command: sh run_validator_client.sh

volumes:
    grafana-data:
    prometheus-data:
    boot-node:

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
