data_dir = ".lighthouse"
db_type = "disk"
db_name = "chain_db"
log_file = ""

[network]
network_dir = "/home/paul/.lighthouse/network"
listen_address = "127.0.0.1"
libp2p_port = 9000
discovery_address = "127.0.0.1"
discovery_port = 9000
max_peers = 10
boot_nodes = []
client_version = "Lighthouse/v0.1.0-unstable/x86_64-linux"
topics = []

[rpc]
enabled = false
listen_address = "127.0.0.1"
port = 5051

[http]
enabled = false
listen_address = "127.0.0.1"
listen_port = "5052"
