data_dir = ".lighthouse"
db_type = "disk"
db_name = "chain_db"
log_file = ""
spec_constants = "minimal"

[eth1_backend_method]
type = "Interop"

[network]
network_dir = "/root/network"
listen_address = "0.0.0.0"
libp2p_port = 9000
discovery_address = "0.0.0.0"
discovery_port = 9000
max_peers = 10
boot_nodes = []
libp2p_nodes = ["/dns4/localhost/tcp/19000"]
client_version = "Lighthouse/v0.1.0-unstable/x86_64-linux"
topics = []

[rpc]
enabled = true
listen_address = "0.0.0.0"
port = 5051

[rest_api]
enabled = true
listen_address = "0.0.0.0"
port = 5052
