spec_constants = "minimal"

[spec]
base_rewards_per_epoch = 5
deposit_contract_tree_depth = 32
seconds_per_day = 86400
target_committee_size = 4
min_per_epoch_churn_limit = 4
churn_limit_quotient = 65536
shuffle_round_count = 10
min_genesis_active_validator_count = 64
min_genesis_time = 1578009600
min_deposit_amount = 1000000000
max_effective_balance = 32000000000
ejection_balance = 16000000000
effective_balance_increment = 1000000000
genesis_slot = 0
bls_withdrawal_prefix_byte = "0x00"
milliseconds_per_slot = 500
min_attestation_inclusion_delay = 1
min_seed_lookahead = 1
activation_exit_delay = 4
min_validator_withdrawability_delay = 256
persistent_committee_period = 2048
max_epochs_per_crosslink = 4
min_epochs_to_inactivity_penalty = 4
base_reward_factor = 64
whistleblower_reward_quotient = 512
proposer_reward_quotient = 8
inactivity_penalty_quotient = 33554432
min_slashing_penalty_quotient = 32
domain_beacon_proposer = 0
domain_randao = 1
domain_attestation = 2
domain_deposit = 3
domain_voluntary_exit = 4
domain_transfer = 5
boot_nodes = []
network_id = 2
